# Generated by Django 4.0.1 on 2022-01-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField()),
                ('number', models.IntegerField(default=0)),
                ('operator', models.CharField(default='-', max_length=1)),
                ('bill_type', models.CharField(default='N/A', max_length=30)),
                ('bill_comment', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
