# Generated by Django 4.0.1 on 2022-02-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_collector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='N/A', max_length=30)),
                ('bank_name', models.CharField(default='N/A', max_length=30)),
                ('number', models.IntegerField(default=0)),
                ('outcome', models.BooleanField(default=True)),
                ('income', models.BooleanField(default=False)),
                ('ivc_type', models.CharField(default='N/A', max_length=30)),
                ('ivc_comment', models.CharField(default='N/A', max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='BillItem',
        ),
    ]
