# Generated by Django 4.0.1 on 2022-03-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_collector', '0003_alter_invoice_date_alter_invoice_outcome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='income',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='outcome',
        ),
        migrations.AddField(
            model_name='invoice',
            name='direction',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
