# Generated by Django 4.0.1 on 2022-03-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_collector', '0004_remove_invoice_income_remove_invoice_outcome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='bank_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='direction',
            field=models.CharField(default='outcome', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.FloatField(),
        ),
    ]
